export const FETCH_APPS = ["FETCH_APPS_LOADING", "FETCH_APPS_SUCCESS", "FETCH_APPS_FAIL"];


export const STRETCH_PROGRESS_BAR = "STRETCH_PROGRESS_BAR";

// STEP1: BASIC CONFIGURE
export const CREATE_APP = ["CREATE_APP_LOADING", "CREATE_APP_SUCCESS", "CREATE_APP_FAIL"];
export const UPDATE_APP = ["UPDATE_APP_LOADING", "UPDATE_APP_SUCCESS", "UPDATE_APP_FAIL"];
export const UPDATE_REDUX_APPS = "UPDATE_REDUX_APPS";

// STEP2: MICROSERVICES
export const UPDATE_MICRO_SERVICES = ["UPDATE_MICRO_SERVICES_LOADING", "UPDATE_MICRO_SERVICES_SUCCESS", "UPDATE_MICRO_SERVICES_FAIL"];
// STEP3: SLO
export const FETCH_METRICS = ["FETCH_METRICS_LOADING", "FETCH_METRICS_SUCCESS", "FETCH_METRICS_FAIL"];

// STEP4: MANAGEMENT FEATURES
export const BEGIN_HYPERPILOTING = ["BEGIN_HYPERPILOTING_LOADING", "BEGIN_HYPERPILOTING_SUCCESS", "BEGIN_HYPERPILOTING_FAIL"];

export const FETCH_DIAGNOSTICS = [
  "FETCH_DIAGNOSTICS_LOADING",
  "FETCH_DIAGNOSTICS_SUCCESS",
  "FETCH_DIAGNOSTICS_FAIL",
];

export const FETCH_AVAILABLE_SERVICES = ["FETCH_AVAILABLE_SERVICES_LOADING", "FETCH_AVAILABLE_SERVICES_SUCCESS", "FETCH_AVAILABLE_SERVICES_FAIL"];

export const FETCH_EDIT_APP_LOADING = "FETCH_EDIT_APP_LOADING";
export const FETCH_EDIT_APP_SUCCESS = "FETCH_EDIT_APP_SUCCESS";
export const FETCH_EDIT_APP_FAIL = "FETCH_EDIT_APP_FAIL";

export const ADD_APP = ["ADD_APP_LOADING", "ADD_APP_SUCCESS", "ADD_APP_FAIL"];
export const REMOVE_APP = ["REMOVE_APP_LOADING", "REMOVE_APP_SUCCESS", "REMOVE_APP_FAIL"];

export const UPDATE_RESOURCES_IN_ANALYZER_LOADING = "UPDATE_RESOURCES_IN_ANALYZER_LOADING";
export const UPDATE_RESOURCES_IN_ANALYZER_SUCCESS = "UPDATE_RESOURCES_IN_ANALYZER_SUCCESS";
export const UPDATE_RESOURCES_IN_ANALYZER_FAIL = "UPDATE_RESOURCES_IN_ANALYZER_FAIL";

export const CACHE_SERVICES_IN_FORM = "CACHE_SERVICES_IN_FORM";
