export const FETCH_APPS = ["FETCH_APPS_LOADING", "FETCH_APPS_SUCCESS", "FETCH_APPS_FAIL"];

export const EDIT_SINGLE_APP = "EDIT_SINGLE_APP";
export const SUBMIT_SLO_CONFIG = "SUBMIT_SLO_CONFIG";
export const STRETCH_PROGRESS_BAR = "STRETCH_PROGRESS_BAR";

export const UPDATE_SINGLE_SLO_LOADING = "UPDATE_SINGLE_SLO_LOADING";
export const UPDATE_SINGLE_SLO_SUCCESS = "UPDATE_SINGLE_SLO_SUCCESS";
export const UPDATE_SINGLE_SLO_FAIL = "UPDATE_SINGLE_SLO_FAIL";

export const BEGIN_HYPERPILOTING = [
  "BEGIN_HYPERPILOTING_LOADING",
  "BEGIN_HYPERPILOTING_SUCCESS",
  "BEGIN_HYPERPILOTING_FAIL",
];

export const FETCH_EVENTS = ["FETCH_EVENTS_LOADING", "FETCH_EVENTS_SUCCESS", "FETCH_EVENTS_FAIL"];

export const FETCH_AVAILABLE_SERVICES_LOADING = "FETCH_AVAILABLE_SERVICES_LOADING";
export const FETCH_AVAILABLE_SERVICES_SUCCESS = "FETCH_AVAILABLE_SERVICES_SUCCESS";
export const FETCH_AVAILABLE_SERVICES_FAIL = "FETCH_AVAILABLE_SERVICES_FAIL";


export const FETCH_EDIT_APP_LOADING = "FETCH_EDIT_APP_LOADING";
export const FETCH_EDIT_APP_SUCCESS = "FETCH_EDIT_APP_SUCCESS";
export const FETCH_EDIT_APP_FAIL = "FETCH_EDIT_APP_FAIL";

export const ADD_APP = ["ADD_APP_LOADING", "ADD_APP_SUCCESS", "ADD_APP_FAIL"];
export const REMOVE_APP = ["REMOVE_APP_LOADING", "REMOVE_APP_SUCCESS", "REMOVE_APP_FAIL"];

export const UPDATE_RESOURCES_IN_ANALYZER_LOADING = "UPDATE_RESOURCES_IN_ANALYZER_LOADING";
export const UPDATE_RESOURCES_IN_ANALYZER_SUCCESS = "UPDATE_RESOURCES_IN_ANALYZER_SUCCESS";
export const UPDATE_RESOURCES_IN_ANALYZER_FAIL = "UPDATE_RESOURCES_IN_ANALYZER_FAIL";

export const CACHE_SERVICES_IN_FORM = "CACHE_SERVICES_IN_FORM";
