export const ADD_TO_HYPERPILOT = "ADD_TO_HYPERPILOT";
export const REMOVE_FROM_HYPERPILOT = "REMOVE_FROM_HYPERPILOT";
export const FETCH_APPS_LOADING = "FETCH_APPS_LOADING";
export const FETCH_APPS_SUCCESS = "FETCH_APPS_SUCCESS";
export const FETCH_APPS_FAIL = "FETCH_APPS_FAIL";
export const EDIT_SINGLE_APP = "EDIT_SINGLE_APP";
export const SUBMIT_SLO_CONFIG = "SUBMIT_SLO_CONFIG";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const TOGGLE_EDIT_SLO_MODAL = "TOGGLE_EDIT_SLO_MODAL";
export const STRETCH_PROGRESS_BAR = "STRETCH_PROGRESS_BAR";

export const UPDATE_SINGLE_SLO_LOADING = "UPDATE_SINGLE_SLO_LOADING";
export const UPDATE_SINGLE_SLO_SUCCESS = "UPDATE_SINGLE_SLO_SUCCESS";
export const UPDATE_SINGLE_SLO_FAIL = "UPDATE_SINGLE_SLO_FAIL";

export const BEGIN_HYPER_PILOTING_LOADING = "BEGIN_HYPER_PILOTING_LOADING";
export const BEGIN_HYPER_PILOTING_SUCCESS = "BEGIN_HYPER_PILOTING_SUCCESS";
export const BEGIN_HYPER_PILOTING_FAIL = "BEGIN_HYPER_PILOTING_FAIL";

export const ADD_STEP_NUMBER = "ADD_STEP_NUMBER";
export const MINUS_STEP_NUMBER = "MINUS_STEP_NUMBER";
export const RESET_STEP_NUMBER = "RESET_STEP_NUMBER";

export const FETCH_EVENTS_LOADING = "FETCH_EVENTS_LOADING";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAIL = "FETCH_EVENTS_FAIL";

export const FETCH_AVALIABLE_SERVICES_LOADING = "FETCH_AVALIABLE_SERVICES_LOADING";
export const FETCH_AVALIABLE_SERVICES_SUCCESS = "FETCH_AVALIABLE_SERVICES_SUCCESS";
export const FETCH_AVALIABLE_SERVICES_FAIL = "FETCH_AVALIABLE_SERVICES_FAIL";


export const FETCH_EDIT_APP_LOADING = "FETCH_EDIT_APP_LOADING";
export const FETCH_EDIT_APP_SUCCESS = "FETCH_EDIT_APP_SUCCESS";
export const FETCH_EDIT_APP_FAIL = "FETCH_EDIT_APP_FAIL";


export const ADD_APP_LOADING = "ADD_APP_LOADING";
export const ADD_APP_SUCCESS = "ADD_APP_SUCCESS";
export const ADD_APP_FAIL = "ADD_APP_FAIL";

export const REMOVE_APP_LOADING = "REMOVE_APP_LOADING";
export const REMOVE_APP_SUCCESS = "REMOVE_APP_SUCCESS";
export const REMOVE_APP_FAIL = "REMOVE_APP_FAIL";
